apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-sample-nghr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-sample-nghr
    app.kubernetes.io/part-of: my-app-2
  name: java-sample-nghr
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-sample-nghr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-sample-nghr
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload@sha256:0638f031ac4ec5ec1bac1f85a9f77218e53ba56474c0e49437ec437ca74deaec
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
