apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-sample-ifix
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-sample-ifix
    app.kubernetes.io/part-of: my-app-2
  name: java-sample-ifix
  namespace: mdsaud-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: java-sample-ifix
status:
  loadBalancer: {}
