apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: src-devfile-sample-w4vp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: src-devfile-sample-w4vp
    app.kubernetes.io/part-of: my-app-2
  name: src-devfile-sample-w4vp
  namespace: mdsaud-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: src-devfile-sample-w4vp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: src-devfile-sample-w4vp
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/uidev-user-workload:Syk6v-src-devfile-sample-w4vp
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
