apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: src-devfile-sample-w4vp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: src-devfile-sample-w4vp
    app.kubernetes.io/part-of: my-app-2
  name: src-devfile-sample-w4vp
  namespace: mdsaud-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: src-devfile-sample-w4vp
    weight: 100
status: {}
